### ISSUE TITLE
Woah It seems as though all the monsters inherit from Spooky Ghosties Class (Joke)

### ISSUE THREAD

**Issue by mberlanga** [UCSB-CS56-Projects/cs56-games-roguelike#86] opened 2017-11-07 04:21 UTC
The monsters in game will occasionally disappear when near walls (but their invisible bodies will still remain to be attacked). I believe this is because they are not being redrawn when they make an invalid move. A fix to this would help to unspook the player.

![disappearing monsters](https://user-images.githubusercontent.com/20020479/32477314-06c7a65c-c332-11e7-9ec0-6e169cf135ff.png)
![monster disappeared](https://user-images.githubusercontent.com/20020479/32477320-12d7cf30-c332-11e7-9d30-c68b3f2edb7a.png)
![allmonsterdisappeared](https://user-images.githubusercontent.com/20020479/32477321-166e0e16-c332-11e7-9091-673824e46ca2.png)
![monstersreappeared](https://user-images.githubusercontent.com/20020479/32477324-189bdf88-c332-11e7-9a1a-2743a15c0667.png)

**Comment by xavierholt** [comment] 2017-12-02 21:06
Looks like this is a duplicate of https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/issues/56 (100 XP).  Fixed by https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/pull/88.

+100 XP

**Closed by xavierholt** 2017-12-02 21:06 UTC
